In [1]:
#System Of Linear Equations in python
     #2x+2y+3z+2w=-2
     # 2y+w=0
     # 4x-3y+w=-7   
     # 6x+y-6z-5w=6
import numpy as np

In [2]:
A=np.array([[2,2,3,2],[0,2,0,1],[4,-3,0,1],[6,1,-6,-5]])
b=np.array([-2,0,-7,6])

X=np.linalg.solve(A,b)

In [4]:
X=np.linalg.solve(A,b)
print(X)

[-0.5         1.          0.33333333 -2.        ]


In [6]:
#Solve the above equations using matrix inversion approach
A_inv=np.linalg.inv(A)
X1=np.dot(A_inv,b)

In [7]:
print(A_inv)

print(X1)


[[ 0.12820513 -0.02564103  0.08974359  0.06410256]
 [ 0.1025641   0.17948718 -0.12820513  0.05128205]
 [ 0.31623932 -0.52991453 -0.14529915 -0.00854701]
 [-0.20512821  0.64102564  0.25641026 -0.1025641 ]]
[-0.5         1.          0.33333333 -2.        ]


In [68]:
#Perform the LU Decomposition of the above matrix
from scipy.linalg import lu

In [16]:
P,L,U=lu(A)
print('P: \n',P)
print('L: \n',L)
print('U: \n',U)
print('LU: \n',np.dot(L,U))

P: 
 [[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
L: 
 [[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [ 0.33333333 -0.45454545  1.          0.        ]
 [ 0.         -0.54545455  0.32        1.        ]]
U: 
 [[ 6.          1.         -6.         -5.        ]
 [ 0.         -3.66666667  4.          4.33333333]
 [ 0.          0.          6.81818182  5.63636364]
 [ 0.          0.          0.          1.56      ]]
LU: 
 [[ 6.  1. -6. -5.]
 [ 4. -3.  0.  1.]
 [ 2.  2.  3.  2.]
 [ 0.  2.  0.  1.]]


In [50]:
#Diagonalization of the square matrix
from scipy.linalg import inv,eig

In [77]:
#Input Square Matrix
P=np.array([[2,2,3,2],[0,2,0,1],[4,-3,0,1],[6,1,-6,-5]])

#Calculate Eigen values and Eigen vectors
evals,evecs=eig(P)


In [78]:
print(evals)

[-5.49538520+0.j -3.13217753+0.j  4.78855028+0.j  2.83901244+0.j]


In [79]:
print(evecs)

[[-0.1766478  -0.06458263 -0.76525282  0.21480661]
 [-0.1292218  -0.17675339 -0.02904638 -0.52185384]
 [-0.1182158  -0.37643443 -0.63795288  0.69987227]
 [ 0.96856714  0.90712978 -0.08099729 -0.43784186]]


In [80]:
print(evals)

[-5.49538520+0.j -3.13217753+0.j  4.78855028+0.j  2.83901244+0.j]


In [81]:
print(evecs)

[[-0.1766478  -0.06458263 -0.76525282  0.21480661]
 [-0.1292218  -0.17675339 -0.02904638 -0.52185384]
 [-0.1182158  -0.37643443 -0.63795288  0.69987227]
 [ 0.96856714  0.90712978 -0.08099729 -0.43784186]]


In [82]:
#Diagonalization of the Square Matrix
#input matrix(4*4)

P=np.array([[2,2,3,2],[0,2,0,1],[4,-3,0,1],[6,1,-6,-5]])
eigen_values,eigen_vectors=eig(P)


In [83]:
print(eigen_values)

[-5.49538520+0.j -3.13217753+0.j  4.78855028+0.j  2.83901244+0.j]


In [84]:
print(eigen_vectors)

[[-0.1766478  -0.06458263 -0.76525282  0.21480661]
 [-0.1292218  -0.17675339 -0.02904638 -0.52185384]
 [-0.1182158  -0.37643443 -0.63795288  0.69987227]
 [ 0.96856714  0.90712978 -0.08099729 -0.43784186]]


In [85]:
# Define the Diagonal matrix D using the eigen value array and
# non singular matrix,S as the eigen vector array,finally determining S-inverse
# completes the diagonalization, P=SDS^-1

D=np.array([[eigen_values[0],0,0,0],[0,eigen_values[1],0,0],[0,0,eigen_values[2],0],[0,0,0,eigen_values[0]]])


In [86]:
S=eigen_vectors
S_inv=inv(S)

In [87]:
print(S_inv)


[[-2.17667012  1.39496862  2.40590465  1.11522707]
 [ 2.16609637 -2.24765063 -2.46980395 -0.20626255]
 [-1.02572877 -0.54496423 -0.27504912 -0.29334997]
 [-0.13758249 -1.47005002  0.25608719 -0.1899637 ]]


In [88]:
# Verify the result
Z=S.dot(D.dot(S_inv))

In [89]:
print(Z)

[[ 2.24631169+0.j  4.63180660+0.j  2.54153127+0.j  2.34008892+0.j]
 [-0.59839266+0.j -4.39374350+0.j  1.11380961+0.j  0.17378378+0.j]
 [ 4.80252056+0.j  5.57482206+0.j -1.49376014+0.j  2.10806088+0.j]
 [ 5.49794111+0.j -4.36443035+0.j -5.06549988+0.j -5.69320569+0.j]]


In [90]:
np.rint(Z)

array([[ 2.+0.j,  5.+0.j,  3.+0.j,  2.+0.j],
       [-1.+0.j, -4.+0.j,  1.+0.j,  0.+0.j],
       [ 5.+0.j,  6.+0.j, -1.+0.j,  2.+0.j],
       [ 5.+0.j, -4.+0.j, -5.+0.j, -6.+0.j]])

In [92]:
np.rint(Z)

array([[ 2.+0.j,  5.+0.j,  3.+0.j,  2.+0.j],
       [-1.+0.j, -4.+0.j,  1.+0.j,  0.+0.j],
       [ 5.+0.j,  6.+0.j, -1.+0.j,  2.+0.j],
       [ 5.+0.j, -4.+0.j, -5.+0.j, -6.+0.j]])

In [91]:
np.abs(Z)

array([[ 2.24631169,  4.6318066 ,  2.54153127,  2.34008892],
       [ 0.59839266,  4.3937435 ,  1.11380961,  0.17378378],
       [ 4.80252056,  5.57482206,  1.49376014,  2.10806088],
       [ 5.49794111,  4.36443035,  5.06549988,  5.69320569]])