In [4]:
#System Of Linear Equations in python
     #2x+2y+3z+2w=-2
     # 2y+w=0
     # 4x-3y+w=-7   
     # 6x+y-6z-5w=6
import numpy as np

In [5]:
A=np.array([[2,2,3,2],[0,2,0,1],[4,-3,0,1],[6,1,-6,-5]])
b=np.array([-2,0,-7,6])

X=np.linalg.solve(A,b)

In [6]:
X=np.linalg.solve(A,b)
print(X)

[-0.5         1.          0.33333333 -2.        ]


In [7]:
#Solve the above equations using matrix inversion approach
A_inv=np.linalg.inv(A)
X1=np.dot(A_inv,b)

In [8]:
print(A_inv)

print(X1)


[[ 0.12820513 -0.02564103  0.08974359  0.06410256]
 [ 0.1025641   0.17948718 -0.12820513  0.05128205]
 [ 0.31623932 -0.52991453 -0.14529915 -0.00854701]
 [-0.20512821  0.64102564  0.25641026 -0.1025641 ]]
[-0.5         1.          0.33333333 -2.        ]


In [9]:
#Perform the LU Decomposition of the above matrix
from scipy.linalg import lu

In [16]:
P,L,U=lu(A)
print('P: \n',P)
print('L: \n',L)
print('U: \n',U)
print('LU: \n',np.dot(L,U))

P: 
 [[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
L: 
 [[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [ 0.33333333 -0.45454545  1.          0.        ]
 [ 0.         -0.54545455  0.32        1.        ]]
U: 
 [[ 6.          1.         -6.         -5.        ]
 [ 0.         -3.66666667  4.          4.33333333]
 [ 0.          0.          6.81818182  5.63636364]
 [ 0.          0.          0.          1.56      ]]
LU: 
 [[ 6.  1. -6. -5.]
 [ 4. -3.  0.  1.]
 [ 2.  2.  3.  2.]
 [ 0.  2.  0.  1.]]


In [10]:
#Diagonalization of the square matrix
from scipy.linalg import inv,eig

In [11]:
#Input Square Matrix
P=np.array([[2,2,3,2],[2,4,-1,6],[3,-1,2,8],[2,6,8,-5]])

#Calculate Eigen values and Eigen vectors
evals,evecs=eig(P)


In [12]:
print(evals)

[-12.20262341+0.j  10.85940722+0.j   0.08145340+0.j   4.26176279+0.j]


In [13]:
print(evecs)

[[-0.03586897  0.41759649 -0.90067376  0.11451358]
 [ 0.33333884  0.4961042   0.11588026 -0.79330801]
 [ 0.4857493   0.55545591  0.31414069  0.59735414]
 [-0.80724609  0.52054061  0.276901    0.02677808]]


In [14]:
print(evals)

[-12.20262341+0.j  10.85940722+0.j   0.08145340+0.j   4.26176279+0.j]


In [81]:
print(evecs)

[[-0.1766478  -0.06458263 -0.76525282  0.21480661]
 [-0.1292218  -0.17675339 -0.02904638 -0.52185384]
 [-0.1182158  -0.37643443 -0.63795288  0.69987227]
 [ 0.96856714  0.90712978 -0.08099729 -0.43784186]]


In [15]:
#Diagonalization of the Square Matrix
#input matrix(4*4)

P=np.array([[2,2,3,2],[0,2,0,1],[4,-3,0,1],[6,1,-6,-5]])
eigen_values,eigen_vectors=eig(P)


In [16]:
print(eigen_values)

[-5.49538520+0.j -3.13217753+0.j  4.78855028+0.j  2.83901244+0.j]


In [18]:
print(eigen_vectors)

[[-0.1766478  -0.06458263 -0.76525282  0.21480661]
 [-0.1292218  -0.17675339 -0.02904638 -0.52185384]
 [-0.1182158  -0.37643443 -0.63795288  0.69987227]
 [ 0.96856714  0.90712978 -0.08099729 -0.43784186]]


In [22]:
# Define the Diagonal matrix D using the eigen value array and
# non singular matrix,S as the eigen vector array,finally determining S-inverse
# completes the diagonalization, P=SDS^-1

D=np.array([[eigen_values[0],0,0,0],[0,eigen_values[1],0,0],[0,0,eigen_values[2],0],[0,0,0,eigen_values[3]]])


In [23]:
S=eigen_vectors
S_inv=inv(S)

In [24]:
print(S_inv)


[[-2.17667012  1.39496862  2.40590465  1.11522707]
 [ 2.16609637 -2.24765063 -2.46980395 -0.20626255]
 [-1.02572877 -0.54496423 -0.27504912 -0.29334997]
 [-0.13758249 -1.47005002  0.25608719 -0.1899637 ]]


In [25]:
# Verify the result
Z=S.dot(D.dot(S_inv))

In [28]:
print(Z)

[[  2.00000000e+00+0.j   2.00000000e+00+0.j   3.00000000e+00+0.j
    2.00000000e+00+0.j]
 [  4.73904290e-16+0.j   2.00000000e+00+0.j  -6.84914789e-16+0.j
    1.00000000e+00+0.j]
 [  4.00000000e+00+0.j  -3.00000000e+00+0.j   1.83781664e-16+0.j
    1.00000000e+00+0.j]
 [  6.00000000e+00+0.j   1.00000000e+00+0.j  -6.00000000e+00+0.j
   -5.00000000e+00+0.j]]


In [29]:
np.rint(Z)

array([[ 2.+0.j,  2.+0.j,  3.+0.j,  2.+0.j],
       [ 0.+0.j,  2.+0.j, -0.+0.j,  1.+0.j],
       [ 4.+0.j, -3.+0.j,  0.+0.j,  1.+0.j],
       [ 6.+0.j,  1.+0.j, -6.+0.j, -5.+0.j]])

In [32]:
np.rint(Z)

array([[ 2.+0.j,  2.+0.j,  3.+0.j,  2.+0.j],
       [ 0.+0.j,  2.+0.j, -0.+0.j,  1.+0.j],
       [ 4.+0.j, -3.+0.j,  0.+0.j,  1.+0.j],
       [ 6.+0.j,  1.+0.j, -6.+0.j, -5.+0.j]])

In [30]:
np.abs(Z)

array([[  2.00000000e+00,   2.00000000e+00,   3.00000000e+00,
          2.00000000e+00],
       [  4.73904290e-16,   2.00000000e+00,   6.84914789e-16,
          1.00000000e+00],
       [  4.00000000e+00,   3.00000000e+00,   1.83781664e-16,
          1.00000000e+00],
       [  6.00000000e+00,   1.00000000e+00,   6.00000000e+00,
          5.00000000e+00]])