In [98]:
#Read a matrix A froma csv file and a vector b from another csv file
import numpy as np
import pandas as pd
from scipy.linalg import lu

In [99]:
A=pd.read_csv("C:/Users/user1/Desktop/matrix_data.csv")

In [100]:
b=pd.read_csv("C:/Users/user1/Desktop/constant vector.csv")

In [101]:
print("A:--------------")
print(A)
print("b:---------------")
print(b)

A:--------------
   1  2  3  4
0  8 -2  0  2
1 -2  4  3  6
2  0  3  6 -1
3  2  6 -1  5
b:---------------
   0  1  2   3
0  9  6  2  15


In [122]:
A

1  2  3  4
0  8 -2  0  2
1 -2  4  3  6
2  0  3  6 -1
3  2  6 -1  5

In [102]:
X=np.array(A)
c=np.array(b.transpose())

In [103]:
print(X)
print(c)

[[ 8 -2  0  2]
 [-2  4  3  6]
 [ 0  3  6 -1]
 [ 2  6 -1  5]]
[[ 9]
 [ 6]
 [ 2]
 [15]]


In [104]:
Y=np.linalg.solve(X,c)

In [105]:
print(Y)

[[ 1.34555785]
 [ 1.49173554]
 [-0.31095041]
 [ 0.60950413]]


In [106]:
#Solve the above equations using matrix inversion aproach
X_inv=np.linalg.inv(X)
X1=np.dot(X_inv,c)

In [107]:
print(X_inv)

[[ 0.09349174 -0.07024793  0.04442149  0.05578512]
 [-0.07024793 -0.10743802  0.08264463  0.17355372]
 [ 0.04442149  0.08264463  0.10950413 -0.09504132]
 [ 0.05578512  0.17355372 -0.09504132 -0.04958678]]


In [108]:
print(X1)

[[ 1.34555785]
 [ 1.49173554]
 [-0.31095041]
 [ 0.60950413]]


In [109]:
#perform the LU decomposition of the above matrix
P,L,U=lu(X)
print("P: \n",P)
print("L: \n",L)
print("U: \n",U)
print("LU: \n",np.dot(L,U))

P: 
 [[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]]
L: 
 [[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.          0.46153846  1.          0.        ]
 [-0.25        0.53846154  0.54761905  1.        ]]
U: 
 [[ 8.         -2.          0.          2.        ]
 [ 0.          6.5        -1.          4.5       ]
 [ 0.          0.          6.46153846 -3.07692308]
 [ 0.          0.          0.          5.76190476]]
LU: 
 [[ 8. -2.  0.  2.]
 [ 2.  6. -1.  5.]
 [ 0.  3.  6. -1.]
 [-2.  4.  3.  6.]]


In [116]:
###Diagonalization of the square matrix
from scipy.linalg import inv,eig

In [117]:
#Input Square Matrix
Q=np.array(X)

#Calculate Eigen values and Eigen vectors
evals,evecs=eig(Q)

In [119]:
print(evals)

[ -3.15614169+0.j   6.25296023+0.j   8.98439326+0.j  10.91878820+0.j]


In [120]:
print(evecs)

[[-0.23425601 -0.34263779  0.90908218 -0.03595899]
 [-0.69889917  0.03890237 -0.13771402  0.70075774]
 [ 0.29537495 -0.87561663 -0.24221849  0.29560001]
 [ 0.60779743  0.3382033   0.30973317  0.6482794 ]]


In [110]:
#Define a Diagonal matrix D whose main diagonal elements are eigen values
#and rest of the elenents are zeros
D =np.array([[evals[0],0,0,0],[0,evals[1],0,0],[0,0,evals[2],0],[0,0,0,evals[3]]])

In [111]:
print(D)

[[ -3.15614169+0.j   0.00000000+0.j   0.00000000+0.j   0.00000000+0.j]
 [  0.00000000+0.j   6.25296023+0.j   0.00000000+0.j   0.00000000+0.j]
 [  0.00000000+0.j   0.00000000+0.j   8.98439326+0.j   0.00000000+0.j]
 [  0.00000000+0.j   0.00000000+0.j   0.00000000+0.j  10.91878820+0.j]]


In [112]:
S=evecs
S_inv=inv(S)

In [113]:
print(S_inv)

[[-0.23425601 -0.69889917  0.29537495  0.60779743]
 [-0.34263779  0.03890237 -0.87561663  0.3382033 ]
 [ 0.90908218 -0.13771402 -0.24221849  0.30973317]
 [-0.03595899  0.70075774  0.29560001  0.6482794 ]]


In [114]:
#verify the result
Z=S.dot(D.dot(S_inv))

In [115]:
print(Z)

[[  8.00000000e+00+0.j  -2.00000000e+00+0.j  -3.87374930e-17+0.j
    2.00000000e+00+0.j]
 [ -2.00000000e+00+0.j   4.00000000e+00+0.j   3.00000000e+00+0.j
    6.00000000e+00+0.j]
 [  1.30474743e-15+0.j   3.00000000e+00+0.j   6.00000000e+00+0.j
   -1.00000000e+00+0.j]
 [  2.00000000e+00+0.j   6.00000000e+00+0.j  -1.00000000e+00+0.j
    5.00000000e+00+0.j]]


In [121]:
np.rint(Z)

array([[ 8.+0.j, -2.+0.j, -0.+0.j,  2.+0.j],
       [-2.+0.j,  4.+0.j,  3.+0.j,  6.+0.j],
       [ 0.+0.j,  3.+0.j,  6.+0.j, -1.+0.j],
       [ 2.+0.j,  6.+0.j, -1.+0.j,  5.+0.j]])